parameters:
#    ninja_tooken_tournament.example.class: NinjaTooken\TournamentBundle\Example

services:
#    ninja_tooken_tournament.example:
#        class: %ninja_tooken_tournament.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
