ninja_tooken_clans_old:
    path:  /clan-ninja.php
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: ninja_tooken_clans
        permanent: true

ninja_tooken_clans:
    path:  /clan/{page}
    defaults: { _controller: NinjaTookenClanBundle:Default:liste, page:1 }
    requirements:
        page:  \d*

ninja_tooken_clan_old:
    path:  /clan.php
    defaults: { _controller: NinjaTookenClanBundle:Default:oldClan }

ninja_tooken_clan:
    path:  /clan/{clan_nom}
    defaults: { _controller: NinjaTookenClanBundle:Default:clan }

ninja_tooken_clan_ajouter:
    path:  /clan-ajouter
    defaults: { _controller: NinjaTookenClanBundle:Default:clanAjouter }

ninja_tooken_clan_modifier:
    path:  /clan/{clan_nom}/modifier
    defaults: { _controller: NinjaTookenClanBundle:Default:clanModifier }

ninja_tooken_clan_supprimer:
    path:  /clan/{clan_nom}/supprimer
    defaults: { _controller: NinjaTookenClanBundle:Default:clanSupprimer }

ninja_tooken_clan_editer_switch:
    path:  /clan-editer-switch/{user_nom}
    defaults: { _controller: NinjaTookenClanBundle:Default:clanEditerSwitch }

ninja_tooken_clan_destituer:
    path:  /clan-destituer/{user_nom}
    defaults: { _controller: NinjaTookenClanBundle:Default:clanUtilisateurSupprimer }

ninja_tooken_clan_destituer_shishou:
    path:  /clan-destituer-shishou/{user_nom}
    defaults: { _controller: NinjaTookenClanBundle:Default:clanUtilisateurSupprimerShishou }

ninja_tooken_clan_recruter:
    path:  /compte/clan
    defaults: { _controller: NinjaTookenClanBundle:Default:clanUtilisateurRecruter }

ninja_tooken_clan_recruter_accepter:
    path:  /compte/clan/accepter/{user_nom}/{recruteur_nom}
    defaults: { _controller: NinjaTookenClanBundle:Default:clanUtilisateurRecruterAccepter }

ninja_tooken_clan_recruter_refuser:
    path:  /compte/clan/refuser/{user_nom}/{recruteur_nom}
    defaults: { _controller: NinjaTookenClanBundle:Default:clanUtilisateurRecruterRefuser }

ninja_tooken_clan_recruter_supprimer:
    path:  /compte/clan/{user_nom}/supprimer
    defaults: { _controller: NinjaTookenClanBundle:Default:clanUtilisateurRecruterSupprimer }

ninja_tooken_clan_recruter_ajouter:
    path:  /compte/clan/{user_nom}
    defaults: { _controller: NinjaTookenClanBundle:Default:clanUtilisateurRecruterAjouter }


ninja_tooken_clan_postuler:
    path:  /clan-postuler/{clan_nom}
    defaults: { _controller: NinjaTookenClanBundle:Default:clanUtilisateurPostuler }

ninja_tooken_clan_postuler_supprimer:
    path:  /clan-postuler-supprimer/{clan_nom}
    defaults: { _controller: NinjaTookenClanBundle:Default:clanUtilisateurPostulerSupprimer }