ninja_tooken_clans:
    pattern:  /clan
    defaults: { _controller: NinjaTookenClanBundle:Default:liste }

ninja_tooken_clan:
    pattern:  /clan/{clan_nom}
    defaults: { _controller: NinjaTookenClanBundle:Default:clan }