parameters:
#    ninja_tooken_clan.example.class: NinjaTooken\ClanBundle\Example

services:
    ninjatooken_clan.clan_proposition_listener:
        class: NinjaTooken\ClanBundle\Listener\ClanPropositionListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate }