parameters:
#    ninja_tooken_clan.example.class: NinjaTooken\ClanBundle\Example

services:
#    ninja_tooken_clan.example:
#        class: %ninja_tooken_clan.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
