ninja_tooken_message_old:
    pattern:  /message.php
    defaults: { _controller: NinjaTookenForumBundle:Default:oldMessage }

ninja_tooken_forum_old:
    pattern:  /forum.php
    defaults: { _controller: NinjaTookenForumBundle:Default:oldForum }

ninja_tooken_event:
    pattern:  /event/{page}
    defaults: { _controller: NinjaTookenForumBundle:Default:event, page:1 }
    requirements:
        page:  \d*

ninja_tooken_forum:
    pattern:  /forum
    defaults: { _controller: NinjaTookenForumBundle:Default:forum }

ninja_tooken_forum_search:
    pattern:  /forum/search
    defaults: { _controller: NinjaTookenForumBundle:Default:forumSearch }

ninja_tooken_topic:
    pattern:  /forum/{topic_nom}/{page}
    defaults: { _controller: NinjaTookenForumBundle:Default:topic, page:1 }
    requirements:
        page:  \d*

ninja_tooken_topic_ajouter:
    pattern:  /forum/{topic_nom}/ajouter/
    defaults: { _controller: NinjaTookenForumBundle:Default:topicAjouter }

ninja_tooken_topic_modifier:
    pattern:  /forum/{topic_nom}/modifier/
    defaults: { _controller: NinjaTookenForumBundle:Default:topicModifier }

ninja_tooken_topic_supprimer:
    pattern:  /forum/{topic_nom}/supprimer/
    defaults: { _controller: NinjaTookenForumBundle:Default:topicSupprimer }

ninja_tooken_message:
    pattern:  /forum/{topic_nom}/{message_nom}/{page}
    defaults: { _controller: NinjaTookenForumBundle:Default:message, page:1 }
    requirements:
        page:  \d*

ninja_tooken_message_ajouter:
    pattern:  /forum/{topic_nom}/ajouter/
    defaults: { _controller: NinjaTookenForumBundle:Default:messageAjouter }

ninja_tooken_message_modifier:
    pattern:  /forum/{topic_nom}/{message_nom}/modifier/
    defaults: { _controller: NinjaTookenForumBundle:Default:messageModifier }

ninja_tooken_message_supprimer:
    pattern:  /forum/supprimer/{topic_nom}/{message_nom}
    defaults: { _controller: NinjaTookenForumBundle:Default:messageSupprimer }