parameters:

services:
    ninjatooken.twig.html_purifier:
        class: NinjaTooken\ForumBundle\Twig\HTMLPurifierExtensionNT
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }

    ninjatooken_forum.comment_listener:
        class: NinjaTooken\ForumBundle\Listener\CommentListener
        arguments: ["%akismet.active%", "%akismet.key%", "%akismet.url%"]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postRemove }

    ninjatooken_forum.thread_listener:
        class: NinjaTooken\ForumBundle\Listener\ThreadListener
        tags:
            - { name: doctrine.event_listener, event: postRemove }