parameters:

services:
    ninjatooken.twig.html_purifier:
        class: NinjaTooken\ForumBundle\Twig\HTMLPurifierExtensionNT
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }