parameters:
#    ninja_tooken_forum.example.class: NinjaTooken\ForumBundle\Example

services:
#    ninja_tooken_forum.example:
#        class: %ninja_tooken_forum.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
