imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        handler_id:     session.handler.pdo
    fragments:       ~

services:
    markup.exercise_html_purifier:
        class: FOS\CommentBundle\Markup\HtmlPurifier
        arguments: [ @exercise_html_purifier.custom ]
    pdo:
        class: PDO
        arguments:
            - "mysql:host=%database_host%;port=%database_port%;dbname=%database_name%"
            - "%database_user%"
            - "%database_password%"
    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments: ["@pdo", "%pdo.db_options%"]

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ "FOSCommentBundle", "NinjaTookenCommonBundle" ]
    read_from: "%kernel.root_dir%/../www"
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to: "\.less$"
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

exercise_html_purifier:
    default:
        Cache.SerializerPath: '%kernel.cache_dir%/htmlpurifier'
    custom:
        Core.Encoding: 'UTF-8'
        HTML.Allowed: 'p[style|align],span[style|align],li[style|align],a[href|target],strong,b,em,i,u,strike,br,img[src|width|height|alt|align],legend,fieldset,object[width|height|codebase|classid],param[name|value],embed[type|width|height|src|allowscriptaccess|allowfullscreen],font[face|size|color]'
        HTML.TargetBlank: true
        AutoFormat.Linkify: true
        CSS.AllowedProperties:  'text-decoration,text-align,color,font,font-family,font-size,font-style,font-weight,float,clear'
        HTML.SafeObject: true
        Output.FlashCompat: true
        HTML.FlashAllowFullScreen: true

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: NinjaTooken\UserBundle\Entity\User
    from_email:
        address:        %mail_contact%
        sender_name:    %mail_name%
    service:
        mailer: fos_user.mailer.twig_swift
    resetting:
        email:
            template: NinjaTookenUserBundle:User:resetting.email.twig

fos_comment:
    db_driver: orm
    class:
        model:
            comment: NinjaTooken\ForumBundle\Entity\Comment
            thread: NinjaTooken\ForumBundle\Entity\Thread
    service:
        markup: markup.exercise_html_purifier

# Stof\DoctrineExtensionBundle configuration
stof_doctrine_extensions:
    orm:
        default:
            sluggable: true