jms_security_extra:
    secure_all_services: false
    expressions: true

parameters:
    security.acl.permission.map.class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap
    sonata.admin.security.mask.builder.class: Sonata\AdminBundle\Security\Acl\Permission\MaskBuilder
    sonata.user.admin.user.entity: NinjaTooken\UserBundle\Entity\User
    sonata.user.admin.group.entity: NinjaTooken\UserBundle\Entity\Group

security:
    acl:
        connection: default

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_SONATA_USER_ADMIN_USER_MODERATOR:
            - ROLE_SONATA_USER_ADMIN_USER_LIST
            - ROLE_SONATA_USER_ADMIN_USER_VIEW
            - ROLE_SONATA_USER_ADMIN_USER_CREATE
            - ROLE_SONATA_USER_ADMIN_USER_EDIT
            - ROLE_SONATA_USER_ADMIN_USER_DELETE
        ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_MODERATOR:
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_LIST
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_VIEW
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_CREATE
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_EDIT
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_DELETE
        ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_UTILISATEUR_MODERATOR:
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_UTILISATEUR_LIST
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_UTILISATEUR_VIEW
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_UTILISATEUR_CREATE
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_UTILISATEUR_EDIT
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_UTILISATEUR_DELETE
        ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_POSTULATION_MODERATOR:
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_POSTULATION_LIST
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_POSTULATION_VIEW
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_POSTULATION_CREATE
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_POSTULATION_EDIT
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_POSTULATION_DELETE
        ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_PROPOSITION_MODERATOR:
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_PROPOSITION_LIST
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_PROPOSITION_VIEW
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_PROPOSITION_CREATE
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_PROPOSITION_EDIT
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_PROPOSITION_DELETE
        ROLE_NINJATOOKEN_FORUM_ADMIN_FORUM_MODERATOR:
            - ROLE_NINJATOOKEN_FORUM_ADMIN_FORUM_LIST
            - ROLE_NINJATOOKEN_FORUM_ADMIN_FORUM_VIEW
            - ROLE_NINJATOOKEN_FORUM_ADMIN_FORUM_EDIT
        ROLE_NINJATOOKEN_FORUM_ADMIN_THREAD_MODERATOR:
            - ROLE_NINJATOOKEN_FORUM_ADMIN_THREAD_LIST
            - ROLE_NINJATOOKEN_FORUM_ADMIN_THREAD_VIEW
            - ROLE_NINJATOOKEN_FORUM_ADMIN_THREAD_CREATE
            - ROLE_NINJATOOKEN_FORUM_ADMIN_THREAD_EDIT
            - ROLE_NINJATOOKEN_FORUM_ADMIN_THREAD_DELETE
        ROLE_NINJATOOKEN_FORUM_ADMIN_COMMENT_MODERATOR:
            - ROLE_NINJATOOKEN_FORUM_ADMIN_COMMENT_LIST
            - ROLE_NINJATOOKEN_FORUM_ADMIN_COMMENT_VIEW
            - ROLE_NINJATOOKEN_FORUM_ADMIN_COMMENT_CREATE
            - ROLE_NINJATOOKEN_FORUM_ADMIN_COMMENT_EDIT
            - ROLE_NINJATOOKEN_FORUM_ADMIN_COMMENT_DELETE
        ROLE_NINJATOOKEN_GAME_ADMIN_NINJA_MODERATOR:
            - ROLE_NINJATOOKEN_GAME_ADMIN_NINJA_LIST
            - ROLE_NINJATOOKEN_GAME_ADMIN_NINJA_VIEW
            - ROLE_NINJATOOKEN_GAME_ADMIN_NINJA_CREATE
            - ROLE_NINJATOOKEN_GAME_ADMIN_NINJA_EDIT
            - ROLE_NINJATOOKEN_GAME_ADMIN_NINJA_DELETE
        ROLE_NINJATOOKEN_USER_ADMIN_MESSAGE_MODERATOR:
            - ROLE_NINJATOOKEN_USER_ADMIN_MESSAGE_LIST
            - ROLE_NINJATOOKEN_USER_ADMIN_MESSAGE_VIEW
            - ROLE_NINJATOOKEN_USER_ADMIN_MESSAGE_CREATE
            - ROLE_NINJATOOKEN_USER_ADMIN_MESSAGE_EDIT
            - ROLE_NINJATOOKEN_USER_ADMIN_MESSAGE_DELETE
        ROLE_NINJATOOKEN_USER_ADMIN_MESSAGE_USER_MODERATOR:
            - ROLE_NINJATOOKEN_USER_ADMIN_MESSAGE_USER_LIST
            - ROLE_NINJATOOKEN_USER_ADMIN_MESSAGE_USER_VIEW
            - ROLE_NINJATOOKEN_USER_ADMIN_MESSAGE_USER_CREATE
            - ROLE_NINJATOOKEN_USER_ADMIN_MESSAGE_USER_EDIT
            - ROLE_NINJATOOKEN_USER_ADMIN_MESSAGE_USER_DELETE
        ROLE_NINJATOOKEN_USER_ADMIN_FRIEND_MODERATOR:
            - ROLE_NINJATOOKEN_USER_ADMIN_FRIEND_LIST
            - ROLE_NINJATOOKEN_USER_ADMIN_FRIEND_VIEW
            - ROLE_NINJATOOKEN_USER_ADMIN_FRIEND_CREATE
            - ROLE_NINJATOOKEN_USER_ADMIN_FRIEND_EDIT
            - ROLE_NINJATOOKEN_USER_ADMIN_FRIEND_DELETE
        ROLE_NINJATOOKEN_USER_ADMIN_CAPTURE_MODERATOR:
            - ROLE_NINJATOOKEN_USER_ADMIN_CAPTURE_LIST
            - ROLE_NINJATOOKEN_USER_ADMIN_CAPTURE_VIEW
            - ROLE_NINJATOOKEN_USER_ADMIN_CAPTURE_CREATE
            - ROLE_NINJATOOKEN_USER_ADMIN_CAPTURE_EDIT
            - ROLE_NINJATOOKEN_USER_ADMIN_CAPTURE_DELETE
        ROLE_NINJATOOKEN_USER_ADMIN_DETECTION_MODERATOR:
            - ROLE_NINJATOOKEN_USER_ADMIN_DETECTION_LIST
        ROLE_SONATA_USER_ADMIN_USER_ADMIN:
            - ROLE_SONATA_USER_ADMIN_USER_EXPORT
        ROLE_SONATA_USER_ADMIN_GROUP_ADMIN:
            - ROLE_SONATA_USER_ADMIN_GROUP_LIST
            - ROLE_SONATA_USER_ADMIN_GROUP_VIEW
            - ROLE_SONATA_USER_ADMIN_GROUP_CREATE
            - ROLE_SONATA_USER_ADMIN_GROUP_EDIT
            - ROLE_SONATA_USER_ADMIN_GROUP_DELETE
            - ROLE_SONATA_USER_ADMIN_GROUP_EXPORT
        ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_ADMIN:
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_EXPORT
        ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_UTILISATEUR_ADMIN:
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_UTILISATEUR_EXPORT
        ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_POSTULATION_ADMIN:
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_POSTULATION_EXPORT
        ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_UTILISATEUR_PROPOSITION_ADMIN:
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_PROPOSITION_EXPORT
        ROLE_NINJATOOKEN_FORUM_ADMIN_FORUM_ADMIN:
            - ROLE_NINJATOOKEN_FORUM_ADMIN_FORUM_CREATE
            - ROLE_NINJATOOKEN_FORUM_ADMIN_FORUM_DELETE
            - ROLE_NINJATOOKEN_FORUM_ADMIN_FORUM_EXPORT
        ROLE_NINJATOOKEN_FORUM_ADMIN_THREAD_ADMIN:
            - ROLE_NINJATOOKEN_FORUM_ADMIN_THREAD_EXPORT
        ROLE_NINJATOOKEN_FORUM_ADMIN_COMMENT_ADMIN:
            - ROLE_NINJATOOKEN_FORUM_ADMIN_COMMENT_EXPORT
        ROLE_NINJATOOKEN_GAME_ADMIN_NINJA_ADMIN:
            - ROLE_NINJATOOKEN_GAME_ADMIN_NINJA_EXPORT
        ROLE_NINJATOOKEN_USER_ADMIN_MESSAGE_ADMIN:
            - ROLE_NINJATOOKEN_USER_ADMIN_MESSAGE_EXPORT
        ROLE_NINJATOOKEN_USER_ADMIN_MESSAGE_USER_ADMIN:
            - ROLE_NINJATOOKEN_USER_ADMIN_MESSAGE_USER_EXPORT
        ROLE_NINJATOOKEN_USER_ADMIN_FRIEND_ADMIN:
            - ROLE_NINJATOOKEN_USER_ADMIN_FRIEND_EXPORT
        ROLE_NINJATOOKEN_USER_ADMIN_CAPTURE_ADMIN:
            - ROLE_NINJATOOKEN_USER_ADMIN_CAPTURE_EXPORT

        # les roles qui seront utilisés
        ROLE_MODERATOR:
            - ROLE_USER
            - ROLE_SONATA_ADMIN
            - ROLE_SONATA_USER_ADMIN_USER_MODERATOR
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_MODERATOR
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_UTILISATEUR_MODERATOR
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_POSTULATION_MODERATOR
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_PROPOSITION_MODERATOR
            - ROLE_NINJATOOKEN_FORUM_ADMIN_FORUM_MODERATOR
            - ROLE_NINJATOOKEN_FORUM_ADMIN_THREAD_MODERATOR
            - ROLE_NINJATOOKEN_FORUM_ADMIN_COMMENT_MODERATOR
            - ROLE_NINJATOOKEN_GAME_ADMIN_NINJA_MODERATOR
            - ROLE_NINJATOOKEN_USER_ADMIN_MESSAGE_MODERATOR
            - ROLE_NINJATOOKEN_USER_ADMIN_MESSAGE_USER_MODERATOR
            - ROLE_NINJATOOKEN_USER_ADMIN_FRIEND_MODERATOR
            - ROLE_NINJATOOKEN_USER_ADMIN_CAPTURE_MODERATOR
            - ROLE_NINJATOOKEN_USER_ADMIN_DETECTION_MODERATOR
        ROLE_ADMIN:
            - ROLE_MODERATOR
            - ROLE_SONATA_USER_ADMIN_USER_ADMIN
            - ROLE_SONATA_USER_ADMIN_GROUP_ADMIN
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_ADMIN
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_UTILISATEUR_ADMIN
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_POSTULATION_ADMIN
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_PROPOSITION_ADMIN
            - ROLE_NINJATOOKEN_FORUM_ADMIN_FORUM_ADMIN
            - ROLE_NINJATOOKEN_FORUM_ADMIN_THREAD_ADMIN
            - ROLE_NINJATOOKEN_FORUM_ADMIN_COMMENT_ADMIN
            - ROLE_NINJATOOKEN_GAME_ADMIN_NINJA_ADMIN
            - ROLE_NINJATOOKEN_USER_ADMIN_MESSAGE_ADMIN
            - ROLE_NINJATOOKEN_USER_ADMIN_MESSAGE_USER_ADMIN
            - ROLE_NINJATOOKEN_USER_ADMIN_FRIEND_ADMIN
            - ROLE_NINJATOOKEN_USER_ADMIN_CAPTURE_ADMIN
            - ROLE_NINJATOOKEN_USER_ADMIN_DETECTION_MODERATOR
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH
        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT

    providers:
        fos_userbundle:
            id: fos_user.user_manager
        my_fos_facebook_provider:
            id: my.facebook.user
        chainprovider:
            chain:
                providers: [fos_userbundle, my_fos_facebook_provider]

    firewalls:
        admin:
            switch_user:        true
            context:            user
            pattern:      /daFuckingAdmin(.*)
            form_login:
                provider:       fos_userbundle
                remember_me:    true
                login_path:     sonata_user_admin_security_login
                use_forward:    false
                check_path:     sonata_user_admin_security_check
                failure_path:   null
            logout:
                path:   sonata_user_admin_security_logout
                target: ninja_tooken_homepage
            anonymous:    true

        main:
            switch_user:        true
            context:            user
            pattern: .*
            form_login:
                provider: fos_userbundle
                remember_me: true
                csrf_provider: form.csrf_provider
                check_path: fos_user_security_check
                login_path: fos_user_security_login
                always_use_default_target_path: false
                default_target_path:            ninja_tooken_homepage
                target_path_parameter:          _target_path
            fos_facebook:
                app_url: ""
                server_url: "http://www.ninjatooken.com"
                login_path: _security_login_facebook
                check_path: _security_check_facebook
                provider: my_fos_facebook_provider
                default_target_path: /
            logout:
                path:   fos_user_security_logout
                target: ninja_tooken_homepage
            anonymous:    true
            remember_me:
                key:    %secret%
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~
                user_providers: [fos_userbundle]
                always_remember_me: false
                remember_me_parameter: _remember_me
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/(fr|en)/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(fr|en)/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(fr|en)/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(fr|en)/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(fr|en)/user/new$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(fr|en)/user/check-confirmation-email$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(fr|en)/user/confirm/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(fr|en)/user/confirmed$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(fr|en)/user/request-reset-password$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(fr|en)/user/send-resetting-email$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(fr|en)/user/check-resetting-email$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(fr|en)/user/reset-password/, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/(fr|en)/compte, role: ROLE_USER }

        - { path: ^/daFuckingAdmin, role: [ROLE_MODERATOR, ROLE_ADMIN] }

        - { path: ^/daFuckingAdmin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/daFuckingAdmin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/daFuckingAdmin/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # The WDT has to be allowed to anonymous users to avoid requiring the login with the AJAX request
        - { path: ^/_wdt/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler/, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # AsseticBundle paths used when using the controller for assets
        - { path: ^/js/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/css/, role: IS_AUTHENTICATED_ANONYMOUSLY }