jms_security_extra:
    secure_all_services: false
    expressions: true

parameters:
    security.acl.permission.map.class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap
    sonata.admin.security.mask.builder.class: Sonata\AdminBundle\Security\Acl\Permission\MaskBuilder
    sonata.user.admin.user.entity: NinjaTooken\UserBundle\Entity\User
    sonata.user.admin.group.entity: NinjaTooken\UserBundle\Entity\Group

security:
    acl:
        connection: default

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_SONATA_USER_ADMIN_USER_MODERATOR:
            - ROLE_SONATA_USER_ADMIN_USER_LIST
            - ROLE_SONATA_USER_ADMIN_USER_VIEW
            - ROLE_SONATA_USER_ADMIN_USER_CREATE
            - ROLE_SONATA_USER_ADMIN_USER_EDIT
        ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_MODERATOR:
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_LIST
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_VIEW
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_CREATE
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_EDIT
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_DELETE
        ROLE_NINJATOOKEN_FORUM_ADMIN_FORUM_MODERATOR:
            - ROLE_NINJATOOKEN_FORUM_ADMIN_FORUM_LIST
            - ROLE_NINJATOOKEN_FORUM_ADMIN_FORUM_VIEW
            - ROLE_NINJATOOKEN_FORUM_ADMIN_FORUM_EDIT
        ROLE_NINJATOOKEN_FORUM_ADMIN_THREAD_MODERATOR:
            - ROLE_NINJATOOKEN_FORUM_ADMIN_THREAD_LIST
            - ROLE_NINJATOOKEN_FORUM_ADMIN_THREAD_VIEW
            - ROLE_NINJATOOKEN_FORUM_ADMIN_THREAD_CREATE
            - ROLE_NINJATOOKEN_FORUM_ADMIN_THREAD_EDIT
            - ROLE_NINJATOOKEN_FORUM_ADMIN_THREAD_DELETE
        ROLE_NINJATOOKEN_FORUM_ADMIN_COMMENT_MODERATOR:
            - ROLE_NINJATOOKEN_FORUM_ADMIN_COMMENT_LIST
            - ROLE_NINJATOOKEN_FORUM_ADMIN_COMMENT_VIEW
            - ROLE_NINJATOOKEN_FORUM_ADMIN_COMMENT_CREATE
            - ROLE_NINJATOOKEN_FORUM_ADMIN_COMMENT_EDIT
            - ROLE_NINJATOOKEN_FORUM_ADMIN_COMMENT_DELETE
        ROLE_SONATA_USER_ADMIN_USER_ADMIN:
            - ROLE_SONATA_USER_ADMIN_USER_DELETE
            - ROLE_SONATA_USER_ADMIN_USER_EXPORT
        ROLE_SONATA_USER_ADMIN_GROUP_ADMIN:
            - ROLE_SONATA_USER_ADMIN_GROUP_LIST
            - ROLE_SONATA_USER_ADMIN_GROUP_VIEW
            - ROLE_SONATA_USER_ADMIN_GROUP_CREATE
            - ROLE_SONATA_USER_ADMIN_GROUP_EDIT
            - ROLE_SONATA_USER_ADMIN_GROUP_DELETE
            - ROLE_SONATA_USER_ADMIN_GROUP_EXPORT
        ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_ADMIN:
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_EXPORT
        ROLE_NINJATOOKEN_FORUM_ADMIN_FORUM_ADMIN:
            - ROLE_NINJATOOKEN_FORUM_ADMIN_FORUM_CREATE
            - ROLE_NINJATOOKEN_FORUM_ADMIN_FORUM_DELETE
            - ROLE_NINJATOOKEN_FORUM_ADMIN_FORUM_EXPORT
        ROLE_NINJATOOKEN_FORUM_ADMIN_THREAD_ADMIN:
            - ROLE_NINJATOOKEN_FORUM_ADMIN_THREAD_EXPORT
        ROLE_NINJATOOKEN_FORUM_ADMIN_COMMENT_ADMIN:
            - ROLE_NINJATOOKEN_FORUM_ADMIN_COMMENT_EXPORT
        # les roles qui seront utilisés
        ROLE_MODERATOR:
            - ROLE_USER
            - ROLE_SONATA_USER_ADMIN_USER_MODERATOR
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_MODERATOR
            - ROLE_NINJATOOKEN_FORUM_ADMIN_FORUM_MODERATOR
            - ROLE_NINJATOOKEN_FORUM_ADMIN_THREAD_MODERATOR
            - ROLE_NINJATOOKEN_FORUM_ADMIN_COMMENT_MODERATOR
        ROLE_ADMIN:
            - ROLE_MODERATOR
            - ROLE_SONATA_USER_ADMIN_USER_ADMIN
            - ROLE_SONATA_USER_ADMIN_GROUP_ADMIN
            - ROLE_NINJATOOKEN_CLAN_ADMIN_CLAN_ADMIN
            - ROLE_NINJATOOKEN_FORUM_ADMIN_FORUM_ADMIN
            - ROLE_NINJATOOKEN_FORUM_ADMIN_THREAD_ADMIN
            - ROLE_NINJATOOKEN_FORUM_ADMIN_COMMENT_ADMIN
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH
        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT

    providers:
        fos_userbundle:
            id: fos_user.user_manager
        chainprovider:
            chain:
                providers: [fos_userbundle, fos_facebook_provider]
        fos_facebook_provider:
            id: fos_facebook.user.login

    firewalls:
        admin:
            switch_user:        true
            context:            user
            pattern:      /daFuckingAdmin(.*)
            form_login:
                provider:       fos_userbundle
                login_path:     /daFuckingAdmin/login
                use_forward:    false
                check_path:     /daFuckingAdmin/login_check
                failure_path:   null
            logout:
                path:   /daFuckingAdmin/logout
            anonymous:    true

        main:
            switch_user:        true
            context:            user
            pattern: .*
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                check_path: fos_user_security_check
                login_path: fos_user_security_login
                always_use_default_target_path: false
                default_target_path:            ninja_tooken_user_messagerie
                use_referer:                    true
                use_forward:			false
            fos_facebook:
                app_url: ""
                server_url: "http://www.ninjatooken.com"
                login_path: fos_user_security_login
                check_path: /facebook/login_check
                provider: fos_facebook_provider
                default_target_path: ninja_tooken_user_messagerie
            logout:
                path:   fos_user_security_logout
                target: ninja_tooken_homepage
            anonymous:    true
            remember_me:
                key:    %secret%
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/(fr|en)/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(fr|en)/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(fr|en)/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(fr|en)/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(fr|en)/user/new$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(fr|en)/user/check-confirmation-email$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(fr|en)/user/confirm/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(fr|en)/user/confirmed$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(fr|en)/user/request-reset-password$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(fr|en)/user/send-resetting-email$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(fr|en)/user/check-resetting-email$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(fr|en)/user/reset-password/, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/daFuckingAdmin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/daFuckingAdmin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/daFuckingAdmin/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/daFuckingAdmin, role: [ROLE_MODERATOR, ROLE_ADMIN] }

        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # The WDT has to be allowed to anonymous users to avoid requiring the login with the AJAX request
        - { path: ^/_wdt/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler/, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # AsseticBundle paths used when using the controller for assets
        - { path: ^/js/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/css/, role: IS_AUTHENTICATED_ANONYMOUSLY }