jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        chainprovider:
            chain:
                providers: [fos_userbundle, fos_facebook_provider]
        fos_facebook_provider:
            id: fos_facebook.user.login

    firewalls:
        main:
            pattern: ^/
            fos_facebook:
                app_url: "http://apps.facebook.com/this-is-my-awesome-app"
                server_url: "http://www.ninjatooken.com"
                login_path: /user/login
                check_path: /facebook/login_check
                provider: fos_facebook_provider
                default_target_path: ninja_tooken_user_messagerie
            form_login:
                csrf_provider: form.csrf_provider
                check_path: fos_user_security_check
                login_path: fos_user_security_login
                default_target_path: ninja_tooken_user_messagerie
                provider: fos_userbundle
            logout:
                path:   fos_user_security_logout
                target: ninja_tooken_homepage
            anonymous:    true
            remember_me:
                key:    %secret%
            provider:   fos_userbundle

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }