services:
    ninja_tooken_game.admin.ninja:
        class: NinjaTooken\GameBundle\Admin\NinjaAdmin
        arguments: [~, NinjaTooken\GameBundle\Entity\Ninja, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Ninja}
