ninja_tooken_game_unity_update:
    path:  /bundles/ninjatookengame/xml/game/update.php
    defaults: { _controller: NinjaTookenGameBundle:Unity:update }

ninja_tooken_game_unity_connect:
    path:  /bundles/ninjatookengame/xml/game/connect.php
    defaults: { _controller: NinjaTookenGameBundle:Unity:connect }