services:
    sonata.user.admin.user:
        class: Sonata\UserBundle\Admin\Entity\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: user, label: User }
        arguments: [null, NinjaTooken\UserBundle\Entity\User, null]
    sonata.user.admin.group:
        class: Sonata\UserBundle\Admin\Entity\GroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: user, label: Group }
        arguments: [null, NinjaTooken\UserBundle\Entity\Group, null]