services:
    sonata.user.admin.user:
        class: NinjaTooken\UserBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: user, label: User }
        arguments: [null, NinjaTooken\UserBundle\Entity\User, null]