ninja_tooken_user_old:
    pattern:  /utilisateur.php
    defaults: { _controller: NinjaTookenUserBundle:Default:oldUser }

ninja_tooken_user_search:
    pattern:  /fiche/search
    defaults: { _controller: NinjaTookenUserBundle:Default:userSearch }

ninja_tooken_user_fiche:
    pattern:  /fiche/{user_nom}/{page}
    defaults: { _controller: NinjaTookenUserBundle:Default:fiche, page:1 }
    requirements:
        page:  \d*

ninja_tooken_user_messagerie_envoi:
    pattern:  /compte/messagerie/envoi/{page}
    defaults: { _controller: NinjaTookenUserBundle:Default:messagerieEnvoi, page:1 }
    requirements:
        page:  \d*

ninja_tooken_user_messagerie:
    pattern:  /compte/messagerie/{page}
    defaults: { _controller: NinjaTookenUserBundle:Default:messagerie, page:1 }
    requirements:
        page:  \d*

ninja_tooken_user_find:
    pattern:  /compte/messagerie/user/find
    defaults: { _controller: NinjaTookenUserBundle:Default:userFind }
    requirements:
        _method:  GET

ninja_tooken_user_parametres:
    pattern:  /compte/parametres
    defaults: { _controller: NinjaTookenUserBundle:Default:parametres }

ninja_tooken_user_amis:
    pattern:  /compte/amis/{page}
    defaults: { _controller: NinjaTookenUserBundle:Default:amis, page:1 }
    requirements:
        page:  \d*

ninja_tooken_user_amis_demande:
    pattern:  /compte/amis/demande/{page}
    defaults: { _controller: NinjaTookenUserBundle:Default:amisDemande, page:1 }
    requirements:
        page:  \d*

ninja_tooken_user_amis_confirmer:
    pattern:  /compte/amis/confirm/{user_nom}
    defaults: { _controller: NinjaTookenUserBundle:Default:amisConfirmer }

ninja_tooken_user_amis_bloquer:
    pattern:  /compte/amis/block/{user_nom}
    defaults: { _controller: NinjaTookenUserBundle:Default:amisBloquer }

ninja_tooken_user_captures:
    pattern:  /compte/captures/{page}
    defaults: { _controller: NinjaTookenUserBundle:Default:captures, page:1 }
    requirements:
        page:  \d*

ninja_tooken_user_captures_supprimer:
    pattern:  /compte/captures/{id}/supprimer/
    defaults: { _controller: NinjaTookenUserBundle:Default:capturesSupprimer }
    requirements:
        page:  \d*

_security_check_facebook:
    pattern:   /facebook/login_check
    defaults:  { _controller: NinjaTookenUserBundle:User:loginFb }

_security_facebook_logout:
  pattern:  /facebook/logout

user_couple_fb_with_account:
    pattern: /user/couple/facebook
    defaults: { _controller: NinjaTookenUserBundle:User:connectFacebookWithAccount }