ninja_tooken_user_old:
    path:  /utilisateur.php
    defaults: { _controller: NinjaTookenUserBundle:Default:oldUser }

ninja_tooken_user_find:
    path:  /compte/messagerie/user/find
    defaults: { _controller: NinjaTookenUserBundle:Default:userFind }
    methods: [GET]

ninja_tooken_user_autologin:
    path:  /auto/{autologin}
    defaults: { _controller: NinjaTookenUserBundle:Default:autologin }
    methods: [GET, POST]

ninja_tooken_user_desinscription:
    path:  /desinscription/{email}
    defaults: { _controller: NinjaTookenUserBundle:Default:desinscription }
    methods: [GET, POST]

ninja_tooken_user_fiche:
    path:  /fiche/{user_nom}/{page}
    defaults: { _controller: NinjaTookenUserBundle:Default:fiche, page:1 }
    requirements:
        page:  \d*

ninja_tooken_user_messagerie_envoi:
    path:  /compte/messagerie/envoi/{page}
    defaults: { _controller: NinjaTookenUserBundle:Default:messagerieEnvoi, page:1 }
    requirements:
        page:  \d*

ninja_tooken_user_messagerie:
    path:  /compte/messagerie/{page}
    defaults: { _controller: NinjaTookenUserBundle:Default:messagerie, page:1 }
    requirements:
        page:  \d*

ninja_tooken_user_parametres:
    path:  /compte/parametres
    defaults: { _controller: NinjaTookenUserBundle:Default:parametres }

fos_user_profile_show:
    path:  /compte/parametres
    defaults: { _controller: NinjaTookenUserBundle:Default:parametres }

ninja_tooken_user_parametres_update:
    path:  /compte/parametres/update
    defaults: { _controller: NinjaTookenUserBundle:Default:parametresUpdate }

ninja_tooken_user_parametres_update_avatar:
    path:  /compte/parametres/update-avatar
    defaults: { _controller: NinjaTookenUserBundle:Default:parametresUpdateAvatar }

ninja_tooken_user_parametres_confirm_mail:
    path:  /compte/parametres/confirm-mail
    defaults: { _controller: NinjaTookenUserBundle:Default:parametresConfirmMail }

ninja_tooken_user_parametres_update_password:
    path:  /compte/parametres/update-password
    defaults: { _controller: NinjaTookenUserBundle:Default:parametresUpdatePassword }

ninja_tooken_user_parametres_delete_account:
    path:  /compte/parametres/delete-account
    defaults: { _controller: NinjaTookenUserBundle:Default:parametresDeleteAccount }

ninja_tooken_user_amis:
    path:  /compte/amis/{page}
    defaults: { _controller: NinjaTookenUserBundle:Default:amis, page:1 }
    requirements:
        page:  \d*

ninja_tooken_user_amis_demande:
    path:  /compte/amis/demande/{page}
    defaults: { _controller: NinjaTookenUserBundle:Default:amisDemande, page:1 }
    requirements:
        page:  \d*

ninja_tooken_user_amis_blocked:
    path:  /compte/amis/bloquer/{page}
    defaults: { _controller: NinjaTookenUserBundle:Default:amisBlocked, page:1 }
    requirements:
        page:  \d*

ninja_tooken_user_amis_confirmer:
    path:  /compte/amis/confirm/{id}
    defaults: { _controller: NinjaTookenUserBundle:Default:amisConfirmer }
    requirements:
        id:  \d*

ninja_tooken_user_amis_bloquer_supprimer_tout:
    path:  /compte/amis/block/supprimer-all
    defaults: { _controller: NinjaTookenUserBundle:Default:amisBlockedSupprimer }

ninja_tooken_user_amis_bloquer:
    path:  /compte/amis/block/{id}
    defaults: { _controller: NinjaTookenUserBundle:Default:amisBloquer }
    requirements:
        id:  \d*

ninja_tooken_user_amis_debloquer:
    path:  /compte/amis/debloquer/{id}
    defaults: { _controller: NinjaTookenUserBundle:Default:amisDebloquer }
    requirements:
        id:  \d*

ninja_tooken_user_amis_supprimer:
    path:  /compte/amis/supprimer/{id}
    defaults: { _controller: NinjaTookenUserBundle:Default:amisSupprimer }
    requirements:
        id:  \d*

ninja_tooken_user_amis_demande_supprimer_tout:
    path:  /compte/amis/demande/supprimer-all
    defaults: { _controller: NinjaTookenUserBundle:Default:amisDemandeSupprimer }


ninja_tooken_user_captures:
    path:  /compte/captures/{page}
    defaults: { _controller: NinjaTookenUserBundle:Default:captures, page:1 }
    requirements:
        page:  \d*

ninja_tooken_user_captures_supprimer:
    path:  /compte/captures/{id}/supprimer/
    defaults: { _controller: NinjaTookenUserBundle:Default:capturesSupprimer }
    requirements:
        id:  \d*

_security_check_facebook:
    path:   /facebook/login_check
    defaults:  { _controller: NinjaTookenUserBundle:User:loginCheckFb }

_security_login_facebook:
    path:  /facebook/login
    defaults: { _controller: NinjaTookenUserBundle:User:loginFb }

_security_logout_facebook:
    path:  /facebook/logout
    defaults: { _controller: NinjaTookenUserBundle:User:logoutFb }