ninja_tooken_chat_homepage:
    pattern:  /chat/
    defaults: { _controller: NinjaTookenChatBundle:Default:index }

ninja_tooken_chat_ajax:
    pattern:  /chat/ajax/
    defaults: { _controller: NinjaTookenChatBundle:Default:ajax }
