ninja_tooken_homepage:
    path:  /
    defaults: { _controller: NinjaTookenCommonBundle:Default:index }

ninja_tooken_jouer_old:
    path:  /jouer.php
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: ninja_tooken_jouer
        permanent: true

ninja_tooken_jouer:
    path:  /jouer
    defaults: { _controller: NinjaTookenCommonBundle:Default:jouer }

ninja_tooken_manuel_old:
    path:  /manuel-ninja/{hash}
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: ninja_tooken_manuel
        permanent: true

ninja_tooken_manuel:
    path:  /guide-du-ninja
    defaults: { _controller: NinjaTookenCommonBundle:Default:manuel }

ninja_tooken_reglement_old:
    path:  /reglement.php
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: ninja_tooken_reglement
        permanent: true

ninja_tooken_reglement:
    path:  /regles-respecter
    defaults: { _controller: NinjaTookenCommonBundle:Default:reglement }

ninja_tooken_chat:
    path:  /chat
    defaults: { _controller: NinjaTookenCommonBundle:Default:chat }

ninja_tooken_faq_old:
    path:  /faq.php
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: ninja_tooken_faq_generale
        permanent: true

ninja_tooken_faq_generale:
    path:  /faq-generale
    defaults: { _controller: NinjaTookenCommonBundle:Default:faqGenerale }

ninja_tooken_faq_technique:
    path:  /faq-technique
    defaults: { _controller: NinjaTookenCommonBundle:Default:faqTechnique }

ninja_tooken_team_old:
    path:  /team-ninja-tooken.php
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: ninja_tooken_team
        permanent: true

ninja_tooken_team:
    path:  /team
    defaults: { _controller: NinjaTookenCommonBundle:Default:team }

ninja_tooken_mentions_legales_old:
    path:  /mentions-legales.php
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: ninja_tooken_mentions_legales
        permanent: true

ninja_tooken_mentions_legales:
    path:  /mentions-legales
    defaults: { _controller: NinjaTookenCommonBundle:Default:mentionsLegales }

ninja_tooken_contact_old:
    path:  /nous-contacter.php
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: ninja_tooken_contact
        permanent: true

ninja_tooken_contact:
    path:  /nous-contacter
    defaults: { _controller: NinjaTookenCommonBundle:Default:contact }

ninja_tooken_search:
    path:  /search
    defaults: { _controller: NinjaTookenCommonBundle:Default:search }

