parameters:
#    ninja_tooken_common.example.class: NinjaTooken\CommonBundle\Example

services:
#    ninja_tooken_common.example:
#        class: %ninja_tooken_common.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
